### ISSUE TITLE
"Fix for NoKeyringError: Install keyrings.alt to Resolve Keyring Backend Issue"

### ISSUE THREAD

**Issue by Jay-lee-git** [thomashirtz/notion-scholar#14]
When running the script, I encountered the following error: `keyring.errors.NoKeyringError: No recommended backend was available`. This error occurred because no suitable keyring backend was available on my system.

Solution:

I resolved the issue by installing the keyrings.alt package, which provides alternative keyring backends. This can be done by running the following command:

```bash
pip install keyrings.alt
```
It might be helpful to include this step in the documentation or provide guidance for users on how to install the necessary keyring backends based on their operating system.

Thank you for creating wonderful plugin

**Comment by thomashirtz** [comment]
Thanks for the help !
Can I ask you what OS do you use ? as well as which python version ?
