### ISSUE TITLE
Invalid request URL

### ISSUE THREAD

**Issue by erlendkopp** [thomashirtz/notion-scholar#4]
First of all, thanks so much for creating this amazing tool! This is exactly what I was looking for to easily manage all my references when writing my masters thesis, but unfortunately I can't get it to work.

I have went over the installation procedure several times, and think I am doing everything correctly.
I have installed the ns package with pip, created the integration, set the token, database and bib-file, but when running `ns run`, I get an 'notion_client.errors.APIResponseError: Invalid request URL.'

The connection to ns-scholar is in the Publication DB (I copied the template), and the database-id is set to the URL of this page.
Am I doing something wrong, or are there any solutions to this?

I am doing this on an M2 Mac, from the default zsh terminal. My Notion account is also accessed through my University email, as this grants me a free Education Plus Plan.

Here is the output I get in the terminal, I have also ran `ns inspect-config` first if the information should be useful:

```
erlendkopperud@eduroam-193-157-176-218 ~ % ns inspect-config

config_file_path: /Users/erlendkopperud/Library/Application Support/notion-scholar/config.ini
config_file_exist: True

token: secret_NIA0cY0UAJzxnt5rK1WeNJ4mMhK5FCAOEXpeflefq6A
database_id: https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b
file_path: /Users/erlendkopperud/Documents/Master/refs.bib
erlendkopperud@eduroam-193-157-176-218 ~ %    
erlendkopperud@eduroam-193-157-176-218 ~ % ns run
Traceback (most recent call last):
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_client/client.py", line 118, in _parse_response
    response.raise_for_status()
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/databases/https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b/query'
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/bin/ns", line 8, in <module>
    sys.exit(main())
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_scholar/main.py", line 143, in main
    return run(**config_manager.get_run_kwargs())
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_scholar/run.py", line 35, in run
    key_list = get_publication_key_list_from_database(
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_scholar/notion_api.py", line 104, in get_publication_key_list_from_database
    return get_property_list_from_database(
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_scholar/notion_api.py", line 74, in get_property_list_from_database
    query = notion.databases.query(
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_client/api_endpoints.py", line 132, in query
    return self.parent.request(
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
  File "/Users/erlendkopperud/.pyenv/versions/3.9.16/lib/python3.9/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: Invalid request URL.
```

**Comment by thomashirtz** [comment]
Thank you for your comment !
Did you use the URL of the database ID and not the URL of the page containing the view of the database ? 
Moreover, did you enter only the database_id and not the full URL ? (see the decomposition of the URL below)
`https://www.notion.so/<workspace_name>/<database_id>?v=<view_id>`

**Comment by erlendkopp** [comment]
I did use the URL of the database (the "Publication DB" from the template, although I have also tried it with the "Category DB"), not the board overview/"Bibliography" page.
As seen in the previous comment when I ran `ns inspect-config` the registered URL is:
```
https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b
```
which seems to satisfy the composition you are mentioning, assuming the long hashes are the database id and view id, separated by `?v=`.

Also, when I copy the link from the Notion app, instead of from the browser, the URL gets the additional ending tag `&pvs=4`, but alas I have tried both including and excluding this tag and still get the same error.
I am also stationed in Norway, but I do not see how that could affect the result, as notion uses `.so` and do not seem to have any different URLs depending on this, but maybe it is somehow relevant.

However I noticed that the raised error includes the following URL:
```
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/databases/https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b/query'
```
which has two `https`'s in the URL and seems to be a concatenation of some database API and my database URL. Trying to access this URL in a browser yields the same error name and code as from the terminal output. 
Maybe this is the cause of the issue, that this URL somehow gets concatenated incorrectly? This may be because of when I set the database id, I had to enclose the URL in quotation marks, or I would get an error.

When I tried
```
ns set-config -db https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b
```
I got this error:
```
zsh: no matches found: https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b
```
But when I put it in quotation marks:
```
ns set-config -db 'https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b'
```
It worked.

I do not know if my assumptions are correct, or if this is easy or hard to fix, but thanks for the response and looking into it!

**Comment by thomashirtz** [comment]
The command that was meant to be used in this context is this one :

`ns set-config -db 199bf7f29eb64de3b439ec2796584249`

Because you need to take only the db section of the url `https://www.notion.so/erlendkopp/199bf7f29eb64de3b439ec2796584249?v=ac9d18439dbd4b97ad0d9a38316f9a6b` (as explained in the documentation and my previous message). If it worked with your command it was not on purpose. I may do a URL parser in the future to make notion scholar more flexible though
