### ISSUE TITLE
Feature request: automatically truncate strings that exceed 2000 characters

### ISSUE THREAD

**Issue by ivnle** [thomashirtz/notion-scholar#5]
It seems that Notion's API restricts us to 2000 characters max. For example, trying to push an entry with a long abstract produces the error:

`notion_client.errors.APIResponseError: body failed validation: body.properties.Bibtex.rich_text[0].text.content.length should be ≤ `2000`, instead was `2123`.`

What are your thoughts on automatically truncating long strings? I've been running a preprocessing script before each notion-scholar run to do this, but figure it might be useful as a built-in feature for others.

**Comment by thomashirtz** [comment]
Which version are you using ? Can you give me the bibtex entry that caused that ?
I implemented that some months ago for the abstract, but there is still some issues related to the bibtex string.

I am in for keeping as much information as possible, as it helps a lot when searching a page on notion (as notion indexes the properties)

I think in the future I'll ignore+warn the entries that are too long and create a flag `truncate` for the `run` command to force the upload to database by truncating it if the user wants to upload it anyway. Right now in theory it always truncate if it is too long, and it removes the abstract from the bibtex string if the string is too long. It is possible however that even without the abstract, the bibtex string stays too long, in which case it may cause this error

**Comment by ivnle** [comment]
I used an older version:  0.2.0. Upgrading to the latest release resulted in a successful push after automatically dropping the abstract, which is the expected behavior you described.

I made a small modification to `bibtex.py` to truncate the abstract instead of dropping it completely. This doesn't resolve the point you brought up about the possibility of the bibtex string still being too long after truncating the abstract, but it works well enough for my use case.
```python
def get_bibtex_str(entry: dict) -> str:
    """"""
    copied_entry = dict(entry)
    database = BibDatabase()
    database.entries = [copied_entry]

    bibtex_str = dumps(database)
    if len(bibtex_str) > 2000:
        # copied_entry.pop('abstract', None)
        # warnings.warn(
        #     f'{entry["ID"]} has its bibtex dump too long ({len(bibtex_str)} > 2000). '
        #     f'Because of API limitation of 2000 characters, the abstract tag has '
        #     f'therefore been removed.',
        #     stacklevel=0,
        # )
        # truncate abstract such that len(bibtex_str) <= 2000
        abstract = copied_entry.get('abstract', '')
        chars_to_remove = len(bibtex_str) - 2000
        copied_entry['abstract'] = abstract[:-chars_to_remove]
```

**Comment by thomashirtz** [comment]
Note that the abstract stay in the property and is truncated, it is only for the bibtex string that it is removed. This means that the page still comport abstract information for indexing.

Can you please give me the bibtex entry ?

**Comment by thomashirtz** [comment]
Here is the code that does that. I'll move it to the notion_api.py soon as I feel it is at the wrong place:
https://github.com/thomashirtz/notion-scholar/blob/7b268c49eae46fc4660fc567a42b0c38cffe6f72/notion_scholar/bibtex.py#L80
